### ISSUE TITLE
Make favicon blue

### ISSUE THREAD

**Issue by itstomekk** [getAlby/bitcoin-connect#107]
![image](https://github.com/getAlby/bitcoin-connect/assets/16482809/a00298cf-fa3b-477d-b85f-50c8e0d12147)

The black one doesn't stand out, BC shade of blue is too cool not to put it in favicon.

here are my two suggestions, 100x100 png compressed

![Bitcoin Connect favicon](https://github.com/getAlby/bitcoin-connect/assets/16482809/754958fb-e63a-4ca6-9161-3c1385de355a)

![Bitcoin Connect favicon (1)](https://github.com/getAlby/bitcoin-connect/assets/16482809/88c40885-91a5-4ece-9478-894a6b87bb58)

**Comment by rolznz** [comment]
@itstomekk this is on the framer site, would you like to try updating it?

**Comment by itstomekk** [comment]
good point Roland, I'll go to the source!

**Comment by itstomekk** [comment]
updated

![image](https://github.com/getAlby/bitcoin-connect/assets/16482809/cd1f155b-906b-49cf-90ea-b3f438622696)
