### ISSUE TITLE
NWC app title should be passed in rather than hardcoded

### ISSUE THREAD

**Issue by rolznz** [getAlby/bitcoin-connect#12]
See https://github.com/getAlby/lightning-wallet-connect/blob/26653ccf5ffa4104bcc1ef120f8129d779a8e3ed/src/connectors/lwc-alby-nwc-connector.ts#L22

**Comment by Sakshi-75** [comment]
Hi @rolznz , can I work on this?

**Comment by rolznz** [comment]
Hi @Sakshi-75, sure!

It is probably easiest to support an attribute like `appName` in the `BitcoinConnectElement` class so it can be set on all components. 

Then `AlbyNWCConnector` needs to somehow have access to this property. I don't think we should have to pass it from the button to the modal to the component list. So maybe we should use the zustand store and update it from the `connectedCallback` in `BitcoinConnectElement`.

Then in `BitcoinConnectElement` create another state variable for the app name and subscribe to it from the store. This way it'll be available in `AlbyNWCConnector`.

Finally, the react wrapper should also be updated to pass the property to the bitcoin connect components.

**Comment by AryanParashar24** [comment]
Hey if it is still open can i work onto this

**Comment by rolznz** [comment]
Hi, this was already merged. Thanks!
