### ISSUE TITLE
Fix "or" color and spacing in divider

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/bitcoin-connect#127]
"or" in the divider has way too little contrast. I assume this may be due transparency of the divider itself?
It should be neutral/tertriary color without transparency 

I also propose to increase spacing between "or" and lines by 2x (to 16px), it looks a bit nicer 

![CleanShot 2023-11-27 at 12 09 09@2x](https://github.com/getAlby/bitcoin-connect/assets/68239231/d76135ed-695c-4242-b266-2981e1fa8b9e)

![CleanShot 2023-11-27 at 12 08 30@2x](https://github.com/getAlby/bitcoin-connect/assets/68239231/2c999f62-175d-447c-ad58-baf5d70c9f83)

**Comment by rolznz** [comment]
@stackingsaunter originally we had full opacity and it was too visible. @Alan-AC7 is changing the opacity from 20% to 60% on light mode, is that ok?

**Comment by stackingsaunter** [comment]
@rolznz can only lines have 20% opacity, and not text?

**Comment by stackingsaunter** [comment]
If you want opacity on whole element, make text neutral/primary

**Comment by rolznz** [comment]
We can change it to only apply on the text. @Alan-AC7 could you do that? sorry I already merged your PR.
