### ISSUE TITLE
Move balance display to a separate component

### ISSUE THREAD

**Issue by rolznz** [getAlby/bitcoin-connect#129]
Currently there is a lot of complicated logic whether to fetch the balance or not (especially in the modal). This would be completely removed if we do the fetch from a separate "balance" component instead.

**Comment by rolznz** [comment]
We should have a single balance component that shows a single currency - it could be sats, or USD, or whatever. By clicking on it, you can then pick your currency. Then there is no inconsistency between the button (only shows sats right now) and the modal (which shows two currencies).

Also this balance component can be exposed as a public component, so that actually websites could display this component on their own if they wished to.

**Comment by rolznz** [comment]
The balance component will not have any dependencies on the state and can somehow display the error (maybe hover over it, click it etc. to see more info). It should look ok on both the button and modal.

**Comment by stackingsaunter** [comment]
@rolznz should I design the selector?

**Comment by rolznz** [comment]
@stackingsaunter yes please!
