### ISSUE TITLE
Hitting enter in connection pages does not submit form

### ISSUE THREAD

**Issue by rolznz** [getAlby/bitcoin-connect#170]
(Accessibility) It should submit the form so users do not need to use the mouse to click.

**Comment by Nomishka** [comment]
@rolznz Can I contribute this?

**Comment by rolznz** [comment]
Hi, there is already an in-progress PR here: https://github.com/getAlby/bitcoin-connect/pull/259

**Comment by rolznz** [comment]
Sorry @Nomishka for not updating this issue.

Closing as a duplicate of https://github.com/getAlby/bitcoin-connect/issues/182

**Comment by Nomishka** [comment]
@rolznz Okay
