### ISSUE TITLE
Missing loading status indicator / callback

### ISSUE THREAD

**Issue by ekzyis** [getAlby/bitcoin-connect#175]
As an (impatient) user, I expect to be told if something is loading else I might think that nothing is going to happen or something broke. Even if it's just for a few seconds. In this case, there were around 3 seconds of no user feedback between submitting the form and showing an error (00:09 - 00:12):

https://github.com/getAlby/bitcoin-connect/assets/27162016/7d43ddfc-1364-47f2-9b98-c5f89104ce30

It would be nice if there is a callback `onLoading` like `onConnected` and `onDisconnected` or similar so developers can use these callbacks to build their own loading spinners etc.

**Comment by rolznz** [comment]
@ekzyis there are `onConnecting`, `onConnected` and `onDisconnected` subscription functions exposed by Bitcoin Connect.

I think it would be nice to also add a skeleton loader on the balance component.

Ideally with LNbits though we would add a connection check to see if the connection is valid (by doing an API call). This can be done in the LNbits connector init function, and if the call fails an error should be thrown which will stop Bitcoin Connect from connecting. https://github.com/getAlby/bitcoin-connect/blob/master/src/connectors/LnbitsConnector.ts#L22

**Comment by ekzyis** [comment]
> @ekzyis there are onConnecting, onConnected and onDisconnected subscription functions exposed by Bitcoin Connect.

Oh, I forgot about that one when I created this ticket! Will check it out and report back.
