### ISSUE TITLE
Programmatically access what connector the user is connected to

### ISSUE THREAD

**Issue by rolznz** [getAlby/bitcoin-connect#177]
In the modal we show what connector you're connected to. But you can't access it from outside.

For example with LNbits there stacker news could show "Connected with LNbits". I'm not sure if showing the hostname is good, because that is specific to LNbits and not other connectors. But we could expose some extra info about the current connector in a generic way?

I think it makes more sense to add a function in Bitcoin Connect rather than expose extra info in WebLN (because it is more about the connector than WebLN?)

![image](https://github.com/getAlby/bitcoin-connect/assets/33993199/5725e157-5575-471c-9384-660393342191)

**Comment by ekzyis** [comment]
> For example with LNbits there stacker news could show "Connected with LNbits".

Yeah, something like this (or exactly this) would be great!

> I'm not sure if showing the hostname is good, because that is specific to LNbits and not other connectors.

You're right, I am also not sure.

> I think it makes more sense to add a function in Bitcoin Connect rather than expose extra info in WebLN (because it is more about the connector than WebLN?)

I agree

**Comment by bumi** [comment]
isn't that already possible because I can access the underlaying provider of the webln object? So I can ask the provider?

**Comment by rolznz** [comment]
@bumi we only have access to the alias from WebLN.

In the Bitcoin Connect modal we show the connector name (which comes from the connector config)

![image](https://github.com/getAlby/bitcoin-connect/assets/33993199/1d3359d5-364c-4144-ae08-d09e57681e15)

I think we could add an api call `getConnectorName()`.

**Comment by rolznz** [comment]
Add `getConnectorConfig` to the api, and also push a WebLN spec.

Adding more functions makes the API more complicated and less clear.

Ideally the Bitcoin Connect API should expose a Bitcoin Connect provider class, rather than global functions - something to think about for the next major version.
