### ISSUE TITLE
Add skeleton loader to the balance component while balance is loading

### ISSUE THREAD

**Issue by rolznz** [getAlby/bitcoin-connect#178]
As per https://github.com/getAlby/bitcoin-connect/issues/175 before balance loads, there is currently no indication of loading.

**Comment by NJacksonDev** [comment]
I would like to work on this. Can you assign this to me?

**Comment by rolznz** [comment]
Hi @NJacksonDev please just go ahead and make a PR. Let me know if you need any help.

**Comment by NJacksonDev** [comment]
Will do - thanks!

**Comment by Nomishka** [comment]
@NJacksonDev are you still working on this?

**Comment by rolznz** [comment]
Ah, this was already completed. Sorry for not closing the issue.

**Comment by Nomishka** [comment]
@rolznz No worries!!!
