### ISSUE TITLE
closeModal function should be async

### ISSUE THREAD

**Issue by rolznz** [getAlby/bitcoin-connect#180]
Since the modal does not immediately close, calling `closeModal` and then instantly calling `launchModal` will cause an error.

See https://github.com/getAlby/bitcoin-connect/blob/master/src/api.ts#L260

We should be able to subscribe and listen to the onModalClosed event to resolve the promise. Currently this won't work as it's instantly called when the state changes (when `modalOpen` is set to false). We might need a new `modalClosing` property.

This should be tested to work in an async React `useEffect` cleanup function.

**Comment by bumi** [comment]
I would avoid such properties. 
what is the case for this? why would I call closeModal and then launchModal again? 
isn't that the same in any react app when I call setState() ?

**Comment by rolznz** [comment]
@bumi in React strict mode it calls effects twice, which ek is having problems with (because the modal isn't closed in time before the second effect executes). I suggested to not launch the popup from an effect and instead do it from a user action (like a button press), but he said a lot of their code already uses effects to launch modals.

Alternatively I could just not throw an error if the modal is launched twice.

**Comment by rolznz** [comment]
We should not make Bitcoin Connect more complicated to handle this. Ideally the modal is not launched in a useEffect hook, otherwise the caller can track the state to make sure the modal isn't launched twice in strict mode.
