### ISSUE TITLE
The connect wallet modal needs a cancel or "x" button because I can't close it from mobile.

### ISSUE THREAD

**Issue by mattius459** [getAlby/bitcoin-connect#181]
<img width="324" alt="Screen Shot 2024-01-04 at 7 04 43 AM" src="https://github.com/getAlby/bitcoin-connect/assets/39392504/69d1dcd8-5514-4f55-b0d1-684a7c88f076">

**Comment by harith-hacky03** [comment]
I am ready to fix it.Can you assign me?

**Comment by rolznz** [comment]
@mattius459 this seems to be fixed or at least not an issue for me. Does it still happen for you? what device/OS?

![image](https://github.com/getAlby/bitcoin-connect/assets/33993199/4b8ce463-b33c-4e80-81ea-b42fbc334d94)
