### ISSUE TITLE
Incorrect copy in mobile pay component

### ISSUE THREAD

**Issue by rolznz** [getAlby/bitcoin-connect#183]
See "this.invoice" on final button
![image](https://github.com/getAlby/bitcoin-connect/assets/33993199/26c69944-568d-4d84-98a6-c4bba6dce2d8)

**Comment by harith-hacky03** [comment]
I am ready to fix it . Can you please assign me?

**Comment by harith-hacky03** [comment]
I Fixed it . If you assign me i a ready to pull my request.

**Comment by rolznz** [comment]
Hi @harith-hacky03 please just create a PR. Thanks!

**Comment by harith-hacky03** [comment]
@rolznz  I created the PR can you please check it out. I Hope it helps. Thank you.

**Comment by rolznz** [comment]
Fixed by https://github.com/getAlby/bitcoin-connect/pull/184
