### ISSUE TITLE
Cannot paste in connection string to nostr wallet connect field.

### ISSUE THREAD

**Issue by mattius459** [getAlby/bitcoin-connect#190]
This issue exists both at Nostrudel as well as on the bitcoin-connect page. So it must be a bitcoin connect issue.

<img width="918" alt="Screen Shot 2024-01-11 at 7 28 18 PM" src="https://github.com/getAlby/bitcoin-connect/assets/39392504/5ec98a37-f987-4671-a4ab-b5e1822dc180">
<img width="1270" alt="Screen Shot 2024-01-11 at 7 28 50 PM" src="https://github.com/getAlby/bitcoin-connect/assets/39392504/1fc13b4d-8383-431f-8de4-dc9fb1ecd54d">

**Comment by rolznz** [comment]
Hi @mattius459 

Sorry about the issue you experienced!

The modal overlay didn't have a specific z-index set and it seems it's treated differently in some browser versions (it started happening on Chrome for me). The [fix](https://github.com/getAlby/bitcoin-connect/commit/532563df7745a2678e10271bd4214a9103d75cfa) has already released but Zappy Bird and Nostrudel were not updated.

I've updated Zappy Bird and made a PR for Nostrudel [here](https://github.com/hzrd149/nostrudel/pull/120).

**Comment by rolznz** [comment]
Please let me know if you need any help integrating Bitcoin Connect. I am a big fan of https://payper-q-chatbot.vercel.app/ !

**Comment by mattius459** [comment]
Hi Roland, I see that you can now paste in a string, but it still doesn't work when I try to get Mutiny to work on Zappybird on the Bitcoin Connect page. It just says "loading" and then when I try to start the game it gives me error telling me to connect a wallet. Unsure if this is Mutiny problem or Bitcoin Connect problem.

<img width="975" alt="Screen Shot 2024-01-12 at 7 17 39 AM" src="https://github.com/getAlby/bitcoin-connect/assets/39392504/afefad4d-3356-4dfd-a2b4-94f5e8344f17">

<img width="957" alt="Screen Shot 2024-01-12 at 7 18 20 AM" src="https://github.com/getAlby/bitcoin-connect/assets/39392504/d9f4d802-94ad-471b-bc67-23d2d6b35660">

**Comment by rolznz** [comment]
@mattius459 unfortunately Mutiny does not support all the Nostr Wallet Connect extension methods yet (such as get_info) so it's not functional here.

**Comment by mattius459** [comment]
So you are saying that Mutiny doesn't support budgeted streaming payments currently?

I just need for Mutiny to be able to do auto-authorized (budgeted) payments to my chatGPT bot just like it does with Alby currently. @reneaaron said Mutiny should be able to do that currently and it seems like they should because on their side there is clearly some budgeting configurations they allow right now.

https://payper-q-chatbot.vercel.app/

**Comment by rolznz** [comment]
@mattius459 someone on our team made a similar app you can try: https://chatbot-ui-bitcoin-connect.vercel.app/

I connected it to Mutiny running on my phone and made payments from my PC. With Mutiny, the payments are a bit slow (about 20-30 seconds for me).

**Comment by rolznz** [comment]
Yes, you can! The payment dialog is optional.

**Comment by rolznz** [comment]
I will close this issue for now. Thanks again for raising it @mattius459 and let me know if you need any help. I'd love to use your app on my phone as a PWA which Bitcoin Connect should make it possible.

**Comment by mattius459** [comment]
Hey Roland, one more thing. Can I get the github link to this?

https://chatbot-ui-bitcoin-connect.vercel.app/

**Comment by Alan-AC7** [comment]
@mattius459 here you go https://github.com/Alan-AC7/chatbot-ui-bitcoin-connect.git

**Comment by mattius459** [comment]
Thank you Alan!
