### ISSUE TITLE
Update currency selector UI

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/bitcoin-connect#199]
It would be nice to have a sleek currency selector in the modal so user can see in their own currency

I prepared rough design [HERE](https://www.figma.com/file/a6wCFTpKv5yjNC06bkVZZ9/Bitcoin-Connect?type=design&node-id=1107-3007&mode=design)

![image](https://github.com/getAlby/bitcoin-connect/assets/68239231/c4cb0cab-fc8c-42f0-843f-24faf18ed6c5)

https://github.com/getAlby/bitcoin-connect/assets/68239231/562ec8bc-ebc3-4fb0-a8d1-1e9e692061e0

![CleanShot 2023-12-26 at 03 12 45](https://github.com/getAlby/bitcoin-connect/assets/68239231/e97fe1dc-3f70-43c1-a998-5c5192a1e6a7)

I used [this icons resource](https://www.figma.com/community/file/1048528064393814860/country-flag-icons), but I am sure there's some nice library for this

Nice to have: 
- searching currency by typing, it would automatically select (live search)

Dev conditions defined by @rolznz 
- No assets should be embedded
- Only the bc-currency-switcher component should be edited

**Comment by matjaz** [comment]
This looks awesome. 
@rolznz do you have in mind specific CDN for assets or what do you suggest?
What should be the rules for localization/formatting?

**Comment by matjaz** [comment]
Maybe we could use UTF flag chars.

**Comment by rolznz** [comment]
> Maybe we could use UTF flag chars.

Although it won't look so good, maybe this is best. We are trying to remove external dependencies to keep this library minimal and secure. @stackingsaunter would you be happy with this?

**Comment by rolznz** [comment]
Note: I think there are also some issues with using flags to choose a currency (since some countries can have multiple currencies), but this is a limited list, right? @stackingsaunter

**Comment by matjaz** [comment]
yeah. some countries have multiple currencies and multiple countries share same currency..
I'll prepare PR and we can go from there.
I haven't found a way to get country -> currency mapping using `Intl`. Or it could be hardcoded?

**Comment by stackingsaunter** [comment]
Can this be closed @rolznz ?
