### ISSUE TITLE
HTMLElement is not defined

### ISSUE THREAD

**Issue by Firegodbr** [getAlby/bitcoin-connect#207]
```
import { launchPaymentModal } from "@getalby/bitcoin-connect-react";
const { setPaid } = launchPaymentModal({
            invoice: lightning_pay,
            onPaid: () => {
                onSubmit(values, paymentId);
            },
            onCancelled: () => {
                setIsLoading(false)
                console.log("Payment canceled");
            },
        });
        checkPayment(paymentId, lightning_pay, 10000, checkCancel, () => {
            setPaid({});
        });
```
I'm running this code but I keep getting this error:
 ⨯ node_modules\@getalby\bitcoin-connect\dist\index.modern.js (1:8683) @ eval
 ⨯ ReferenceError: HTMLElement is not defined
 
 It doesn't break the app, but I want to know what it can be done to avoid it

**Comment by rolznz** [comment]
Hi @Firegodbr what framework do you use?

You'll need to make sure you only import and render Bitcoin Connect client-side.

There is some documentation for dynamically importing here: https://github.com/getAlby/bitcoin-connect?tab=readme-ov-file#nextjs--ssr
