### ISSUE TITLE
Relay gets blasted with get_balance requests if NWC service does not implement get_balance command

### ISSUE THREAD

**Issue by SamSamskies** [getAlby/bitcoin-connect#224]
Here's a screenshot from Nostrudel when I use a connection string from my NWC service that does not implement get_balance. I built an [NWC service for Strike](https://github.com/SamSamskies/strike-nwc-service) and the balance is denominated in fiat, so I'm not supporting the get_balance command. I'm responding with error code `NOT_IMPLEMENTED`, but bitcoin-connect still bugs out.

![Screenshot 2024-05-11 at 5 12 25 PM](https://github.com/getAlby/bitcoin-connect/assets/3655410/ab909eee-49d8-4879-a056-0ab5d4d8d98d)

**Comment by rolznz** [comment]
Thanks for the bug report @SamSamskies !
