### ISSUE TITLE
Stuck loading if NWC connection string is not valid

### ISSUE THREAD

**Issue by SamSamskies** [getAlby/bitcoin-connect#225]
I made an NWC connection string in the same format as the example in the nip-47 docs (it doesn't have forward slashes in it) and bitcoin-connect gets stuck loading. The connection string works in Damus though.

![Screenshot 2024-05-11 at 2 45 10 PM](https://github.com/getAlby/bitcoin-connect/assets/3655410/89f4c09c-f2e9-480f-bf0c-2a99a4d71c26)
![Screenshot 2024-05-11 at 2 45 16 PM](https://github.com/getAlby/bitcoin-connect/assets/3655410/5dfd6369-0516-4101-a967-8b4d8bceb3b3)

**Comment by rolznz** [comment]
Thanks @SamSamskies for reporting. Fix here: https://github.com/getAlby/js-sdk/pull/220

I'll update this issue when a bitcoin connect patch is out.
