### ISSUE TITLE
Lightning Node Connect Setup- Fails Silently

### ISSUE THREAD

**Issue by uncleJim21** [getAlby/bitcoin-connect#230]
**Steps to recreate:**
1. Set up pass phrase from LNC
2. Click on Bitcoin Connect Button
3. Attempt to attach to LNC
4. Alert pops up, punch in passphrase
5. Hit enter

**Result:**
No obvious errors thrown to user.
Console shows this error:
```
index.modern.js:1 TypeError: t is not a constructor
    at index.modern.js:1:508
    at p (regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (regeneratorRuntime.js:133:17)
    at Generator.next (regeneratorRuntime.js:74:21)
    at r (asyncToGenerator.js:3:20)
    at l (asyncToGenerator.js:22:9)
```

**Comment by rolznz** [comment]
I unfortunately do not have a wallet with LNC available to debug this at the moment, however this was working fine when I implemented it and there's been no changes since then.

Are you able to connect to other apps using LNC? for example the Alby Browser Extension?

**Comment by rolznz** [comment]
LNC doesn't seem to be working any more (or at least the default server seems to be down). I created an issue here: https://github.com/lightninglabs/lnc-web/issues/113

**Comment by rolznz** [comment]
Edit: I tried LNC again and it works now: 
![image](https://github.com/getAlby/bitcoin-connect/assets/33993199/e9968663-382e-49db-bd3b-5251f30ce57a)

I think something was wrong with the previous pairing phrase I used.

Can you please try again with a new, unused pairing phrase and make sure it's saved correctly?

**Comment by rolznz** [comment]
@uncleJim21 did you get it working? I will close this issue for now as I managed to connect. I would also recommend trying NWC as an alternative to LNC if you can install it on your node.
