### ISSUE TITLE
Mutiny UI changed to get the NWC string. 

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/bitcoin-connect#231]
It is now:

1. Add a new Wallet Connection from Requests --> Edit wallet connections --> Add Connection

![image](https://github.com/getAlby/bitcoin-connect/assets/13707997/bbeccee9-246a-4f81-9783-57cd9781bff8)

**Comment by rolznz** [comment]
Thanks, I see it here:
![image](https://github.com/getAlby/bitcoin-connect/assets/33993199/01820eb3-2540-41ab-b1b6-f36105047264)

I've changed it to `Requests => Create a Wallet Connection`
