### ISSUE TITLE
Add skeleton loader for modal connecting state

### ISSUE THREAD

**Issue by rolznz** [getAlby/bitcoin-connect#34]
Currently shows just a spinner which doesn't look good and causes the modal height to jump. Instead it should show the connected content, with skeleton loaders for any content that is loading.

**Comment by hirenchauhan2** [comment]
I can help on this, could you please guide where exactly I need to make changes? On React wrapper or to the Lit components?

**Comment by rolznz** [comment]
Hi @hirenchauhan2 the change needs to be made on the bc-modal lit component. Thanks!

**Comment by hirenchauhan2** [comment]
@rolznz What do you think of this kind of design for loading state, it's pulse animation from Tailwind. Please share your thoughts on this.

![image](https://github.com/getAlby/bitcoin-connect/assets/8999668/9092dcf1-f920-4ffd-9bca-da5608a9de8b)

**Comment by hirenchauhan2** [comment]
@rolznz Please check the raised PR #70  and let me know if there are any changes needed.

**Comment by hirenchauhan2** [comment]
This is how I mocked the state of the modal

![image](https://github.com/getAlby/bitcoin-connect/assets/8999668/84f8c2b4-11b1-43a2-aa94-7a3a81a480a0)
