### ISSUE TITLE
Add minor icon / hover animations

### ISSUE THREAD

**Issue by rolznz** [getAlby/bitcoin-connect#37]
https://www.figma.com/proto/XYlv0E7SY3R20XHjFcn5kI/Lightning-Connect?page-id=0%3A1&type=design&node-id=55-4168&viewport=1199%2C-1150%2C0.34&t=So5wHGNq4xwfnJsI-1&scaling=min-zoom&starting-point-node-id=55%3A4168&hotspot-hints=0

**Comment by rolznz** [comment]
Partially done, just need new icons from @stackingsaunter to be able to animate the correct parts

**Comment by rolznz** [comment]
Thanks @stackingsaunter !

For contributors: please see existing hover animations on the logout and open link buttons on the help screen.

The new icons have been linked which now has different paths, so we can just animate the path that should be moved.

**Comment by rituraj12797** [comment]
i would like to work on this issue

**Comment by octopols** [comment]
> https://www.figma.com/proto/XYlv0E7SY3R20XHjFcn5kI/Lightning-Connect?page-id=0%3A1&type=design&node-id=55-4168&viewport=1199%2C-1150%2C0.34&t=So5wHGNq4xwfnJsI-1&scaling=min-zoom&starting-point-node-id=55%3A4168&hotspot-hints=0

I've requested access to this file (Hirnaymay2010075@akgec.ac.in)

**Comment by rolznz** [comment]
Hi, there is no need to see the figma, the linked icons were already provided in https://github.com/getAlby/bitcoin-connect/issues/52

**Comment by rolznz** [comment]
Since there are two contributors, I will not assign the issue, please just make a PR if you are interested.

Thank you!

**Comment by rolznz** [comment]
Hi @octopols @rituraj12797 did either of you make any progress?

**Comment by rituraj12797** [comment]
doing now

**Comment by rolznz** [comment]
Fixed in https://github.com/getAlby/bitcoin-connect/commit/edc6c440854f0516db8324d72d23869fde5d2ede
