### ISSUE TITLE
Add mutiny wallet NWC connector

### ISSUE THREAD

**Issue by rolznz** [getAlby/bitcoin-connect#43]
https://app.mutinywallet.com/settings/connections

with the link and some info and an input field for the connection.

**Comment by aashna09** [comment]
Hi, I would like to work on this, can you please assign this to me?

**Comment by rolznz** [comment]
Hi @aashna09 , thanks for offering to work on this. Go ahead!

**Comment by AryanParashar24** [comment]
hey, i would like to work on this 😄😃

**Comment by rolznz** [comment]
Hi @AryanParashar24 I already assigned this issue, but feel free to make a PR. The PR that correctly addresses the issue will be merged.

**Comment by rolznz** [comment]
Hi @AryanParashar24  @aashna09 did either of you make any progress?

**Comment by AryanParashar24** [comment]
Yeah have been working onto it, though got some issues while working bt hope i get to pass em soon 😄

**Comment by AryanParashar24** [comment]
ok so i might be getting a bit wrong in this project as it appears to be nt merging it, please can u specify again in details wht do we have to do in this issue i will imporve the code then within few minutes and go for the PR quickly

**Comment by rolznz** [comment]
@AryanParashar24 currently you can connect to your Alby wallet using the NWC protocol (that is the Alby option in the modal), or a generic NWC URL (allowing connection to any wallet that supports NWC). We would like to make another option that uses Mutiny, but it still uses the same underlying NWC connector.

Mutiny is a great self-custodial wallet and we would like to simplify the flow of getting the NWC URL from Mutiny. So you would add a new component that would give guidance and a link on how to open the correct mutiny URL to setup a connection, then enter it in Bitcoin Connect.
