### ISSUE TITLE
SVG icon viewbox consistency

### ISSUE THREAD

**Issue by rolznz** [getAlby/bitcoin-connect#52]
In figma many of the icons have inconsistent sizing. Should they all be 24x24?

**Comment by stackingsaunter** [comment]
We can actually sync on this - would it be better for you to all have same viewbox but different sizes of the SVG itself (as it is in bitcoin icons originally)?

For me it's important to visually look like in Figma, but I can adjust in how icons are rendered there, just let me know if you'd prefer different sizes to have the same box size

**Comment by rolznz** [comment]
@stackingsaunter I think if the viewbox is the same for all, that will fix the issue, thanks.

**Comment by stackingsaunter** [comment]
All icons are now 24px.
I also made disconnect and link icons to be made of 2 paths, so you can animate it. Let me know if that works and everything is fine @rolznz 

![back](https://github.com/getAlby/bitcoin-connect/assets/68239231/6af05f59-08b0-4dc0-bdfd-0428ddf60cdc)
![close](https://github.com/getAlby/bitcoin-connect/assets/68239231/dff14429-4859-4015-b03d-c1efcbccc60e)
![exit-hover](https://github.com/getAlby/bitcoin-connect/assets/68239231/d5703c33-2067-453f-a2b1-a08003369ae3)
![exit](https://github.com/getAlby/bitcoin-connect/assets/68239231/4b7c3b4e-9628-444f-9bed-78015541e275)
![link-hover](https://github.com/getAlby/bitcoin-connect/assets/68239231/11e0ec4b-6aac-49ed-bb61-2b9d767236d9)
![link](https://github.com/getAlby/bitcoin-connect/assets/68239231/026f16ab-8422-43bd-a718-c3998b81133f)
![question](https://github.com/getAlby/bitcoin-connect/assets/68239231/c7a1bcc2-94b5-48bd-92a0-dd2766d49cd0)

**Comment by rolznz** [comment]
@stackingsaunter is it intended that the svg viewbox is 25x24? should it be 24x24? (you can open and check in a text editor)

**Comment by rolznz** [comment]
fixed in https://github.com/getAlby/bitcoin-connect/commit/fbd43262d7cdfdc3c6c5d5b11d5fda08cfb92cf2

**Comment by stackingsaunter** [comment]
> @stackingsaunter is it intended that the svg viewbox is 25x24? should it be 24x24? (you can open and check in a text editor)

Did you manage to fix it or should I?
