### ISSUE TITLE
Too many colors

### ISSUE THREAD

**Issue by rolznz** [getAlby/bitcoin-connect#53]
From W3modal: they only allow you to set one accent color, everything else is generated.
Now we have many colors, new shades for the ruler lines and help.

How can we make a nice API for users that can easily add 1 or 2 colors and it just looks great? it's too easy for a developer to make something that looks bad right now.

**Comment by stackingsaunter** [comment]
Updated colors: https://www.figma.com/file/a6wCFTpKv5yjNC06bkVZZ9/Bitcoin-Connect-0.2?type=design&node-id=273-1879&mode=design

**Comment by stackingsaunter** [comment]
Some changes I did today @rolznz 

1. Changed a bit shades of neutral gray
2. Icons (except for those inside buttons) have now tertiary gray
3. The only thing using tertiary neutral was the divider. Now it's neutral 500 and 20% opacity, both themes

![CleanShot 2023-09-12 at 12 29 23@2x](https://github.com/getAlby/bitcoin-connect/assets/68239231/ebfe8549-e87d-4613-b3f9-fc670cba6088)
