### ISSUE TITLE
Cleanup & Optimize svgs

### ISSUE THREAD

**Issue by rolznz** [getAlby/bitcoin-connect#55]
Currently SVGs are unoptimized, but we also set colors inside them and sometimes classes. This is quite a mess.

**Comment by stackingsaunter** [comment]
https://github.com/getAlby/bitcoin-connect/issues/52 I used SVGOMG on those, but was not sure about the color. Should I switch it to black?

**Comment by rolznz** [comment]
@stackingsaunter I replace it with "currentColor" anyway. Thanks!
