### ISSUE TITLE
Add mobile wallet connector

### ISSUE THREAD

**Issue by rolznz** [getAlby/bitcoin-connect#56]
Users who see the bitcoin connect button _SHOULD_ in some way be able to connect the wallet they have on their phone and helps build a connection there because the user thinks they should be able to use the wallet they already have. Maybe it does not work in all cases where realtime/frequent payments are required (like Zappy Bird), but for many cases it is OK. We can also somehow notify the user that their wallet does not support some features.

Once clicked, the enable() function would just return true. Some webln functions would be disabled (we can notify there). This would also be a huge timer saver for developers who just want a way to allow users to pay invoices, no matter what method they choose.

We would need to maintain a list of all popular mobile wallets, but hopefully we can start it off and the community can help there if we setup a nice contributing guide.

Bitrefill has something similar in their checkout:
- Pick the wallet
- Some wallets have unique schemes to immediately open them on the right payment page, otherwise a lightning link, or the worst fallback is just "copy invoice".

Another issue: If the user makes a payment from their mobile wallet, how does the site update?
- A backend may receive a webhook from the lightning service (e.g. Alby).
- The backend could send something to the frontend via a websocket.
- The frontend should be able to programmatically call Bitcoin Connect to close or show a success screen.

This is required because there is currently no standard to check a status of an invoice.

**Comment by rolznz** [comment]
Almost nothing in WebLN is possible with mobile connectors - even sending payments you cannot get a preimage back, and then sites will not be able to rely on WebLN.

The only real solution is for these mobile wallets to implement NWC or some other protocol for interaction.

CC @MoritzKa @reneaaron @stackingsaunter @bumi

**Comment by stackingsaunter** [comment]
Yeah, we need a future where most (or a lot) wallets will have NWC :)
