### ISSUE TITLE
Update button padding

### ISSUE THREAD

**Issue by stackingsaunter** [getAlby/bitcoin-connect#59]
Button padding's updated a bit, with a wrap around copy and [updated icon ](https://github.com/getAlby/bitcoin-connect/issues/58)to make it more balanced. 

[Link to Figma](https://www.figma.com/file/a6wCFTpKv5yjNC06bkVZZ9/Bitcoin-Connect?type=design&node-id=273-1868&mode=design&t=RaFDZjoQOMcuZkDd-4)

![CleanShot 2023-09-12 at 12 47 40@2x](https://github.com/getAlby/bitcoin-connect/assets/68239231/1fe853b3-ac3d-444e-9592-66132257b2fc)

**Comment by rolznz** [comment]
Fixed in https://github.com/getAlby/bitcoin-connect/commit/d28779e3b340d282326f5af4d699284b42ade9c1

**Comment by rolznz** [comment]
fixed
