### ISSUE TITLE
Alby NWC button opens up LnBits?

### ISSUE THREAD

**Issue by futurepaul** [getAlby/bitcoin-connect#87]
hey! stoked to try this out in zapplepay. might have a bug tho. alby button goes to this, same "page" as lnbits button

<img width="495" alt="Screenshot 2023-10-24 at 2 16 51 PM" src="https://github.com/getAlby/bitcoin-connect/assets/543668/2113603e-7b8a-4514-880b-ffdb816c7c8e">

**Comment by bumi** [comment]
ohh, thanks for reporting. that's strange, will have a look asap.

**Comment by rolznz** [comment]
@futurepaul sorry for the delay, I am at IDBC this week. Fixed in 2.1.4 (fix here: https://github.com/getAlby/bitcoin-connect/commit/7452f215f5466769cc0b1d10543a0499bb617848)

**Comment by rolznz** [comment]
@futurepaul Zapple Pay currently looks like this:

![image](https://github.com/getAlby/bitcoin-connect/assets/33993199/637102fc-586e-4377-9e35-4378d4cf11e6)

Which is great for Mutiny, but I think the UX could still be improved for users who use a NWC connection with other wallets.

Are you still considering using Bitcoin Connect? or if not, would you be happy to share with us any reasonings?
- Is it missing a feature you need?
- Was it difficult to integrate?
- Or something else?

Sorry for the initial bugs when you initially tried it.

**Comment by rolznz** [comment]
Thanks @futurepaul ! we'll let you know when we have an update on #89
