### ISSUE TITLE
Lit is in dev mode

### ISSUE THREAD

**Issue by futurepaul** [getAlby/bitcoin-connect#88]
running `"@getalby/bitcoin-connect": "^2.1.3",`

<img width="583" alt="Screenshot 2023-10-24 at 3 00 17 PM" src="https://github.com/getAlby/bitcoin-connect/assets/543668/dc3e2395-d087-4ba1-a17e-d690694f9f1f">

https://lit.dev/docs/tools/development/#development-and-production-builds

**Comment by rolznz** [comment]
I think this is a problem with lit - the documentation says you need to explicitly opt-in to dev mode, which I don't do.

There is an outstanding issue https://github.com/getAlby/bitcoin-connect/issues/76 which I'll try to work on and then re-check this.

Thanks!

**Comment by rolznz** [comment]
Fixed in https://github.com/getAlby/bitcoin-connect/pull/106
